#!/bin/bash

# Create our virtual network

# IMPORTANT NOTE: Node names MUST NOT exceed 9 characters.
# This is due to the limitation to 14 characters of interface names

# Group number
GROUPNUMBER=2
# Node configs
CONFIGDIR=myNetwork_cfg
# boot script name
BOOT="boot"
# startup script name
STARTUP="start"
PREFIXBASE="fde4:2"
PREFIXLEN=32

# This function describes the network topology that we want to emulate
function mk_topo {
    echo "@@ Adding links and nodes"
    # Build the network
    # Nodes are creadted on the fly, and their interface are assigned as
    # <node name>-eth<count>, where count starts at 0 and is increased by 1
    # after each new interface
    # e.g. R1-eth0 links to R2-eth0
    # R1-eth1 links to R3-eth0
    add_link R13 R1
    add_link R13 R2
    add_link R1 R2
    add_link R1 R3
    add_link R2 R4
    add_link R3 R4
    add_link R3 R5
    add_link R3 R7
    add_link R4 R5
    add_link R4 R6
    add_link R5 R6
    add_link R5 R7
    add_link R5 R8
    add_link R6 R8
    add_link R7 R8
    add_link R7 R9
    add_link R8 R9
    add_link R9 R10
    add_link R9 R11
    add_link R10 R11
    add_link R10 R12
    add_link R11 R12
    add_link R7 R11

    #echo "@@ Briding the network"
    bridge_node R6 eth3 eb1
    bridge_node R1 eth4 ebG1
    bridge_node R3 eth5 ebG3
    bridge_node R11 eth6 ebG4
    bridge_node R6 eth7 ebG6
}
