#!/bin/bash

# Abort on error // swap with -x to trace execution (debug)
set -e

# Load global config
#source "$(cd "$(dirname "$0")"; pwd -P)/../myNetwork"
ldconfig

# Add loopback address
ip -6 addr add fde4:2:0:bb::b/64 dev lo

# Add the addresses for our public interfaces towards BGP peers
ip link set dev R11-eth0 up
ip -6 addr add fde4:2:0:9b::b/64 dev R11-eth0

ip link set dev R11-eth1 up
ip -6 addr add fde4:2:0:ab::b/64 dev R11-eth1

ip link set dev R11-eth2 up
ip -6 addr add fde4:2:0:bc::b/64 dev R11-eth2

ip link set dev R11-eth3 up
ip -6 addr add fde4:2:0:7b::b/64 dev R11-eth3

ip link set dev ebG4 up
ip -6 addr add fde4:4:f001::2:bebe/64 dev ebG4


# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/r11.api -i /tmp/r11_zebra.pid --v6-rr-semantics &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/r11_ospf.conf -z /tmp/r11.api -i /tmp/r11_ospf6d.pid -A 127.0.0.1 &
# launching bgpd
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/r11_bgp.conf -z /tmp/r11.api -i /tmp/r11_bgpd.pid -A 127.0.0.1


