#!/bin/bash

# Abort on error // swap with -x to trace execution (debug)
set -e

# Load global config
#source "$(cd "$(dirname "$0")"; pwd -P)/../myNetwork"
ldconfig

# Add loopback address
ip -6 addr add fde4:2:0:22::2/64 dev lo

# Add the addresses for our public interfaces towards BGP peers
ip link set dev R2-eth0 up
ip -6 addr add fde4:2:0:2d::2/64 dev R2-eth0

ip link set dev R2-eth1 up
ip -6 addr add fde4:2:0:12::2/64 dev R2-eth1

ip link set dev R2-eth2 up
ip -6 addr add fde4:2:0:24::2/64 dev R2-eth2


# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/r2.api -i /tmp/r2_zebra.pid --v6-rr-semantics &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/r2_ospf.conf -z /tmp/r2.api -i /tmp/r2_ospf6d.pid -A 127.0.0.1 &
# launching bgpd
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/r2_bgp.conf -z /tmp/r2.api -i /tmp/r2_bgpd.pid -A 127.0.0.1

