#!/bin/bash

# Abort on error // swap with -x to trace execution (debug)
set -e

# Load global config
#source "$(cd "$(dirname "$0")"; pwd -P)/../myNetwork"
ldconfig

# Add loopback address
ip -6 addr add fde4:2:0:55::5/64 dev lo

# Add the addresses for our public interfaces towards BGP peers
ip link set dev R5-eth0 up
ip -6 addr add fde4:2:0:35::5/64 dev R5-eth0

ip link set dev R5-eth1 up
ip -6 addr add fde4:2:0:45::5/64 dev R5-eth1

ip link set dev R5-eth2 up
ip -6 addr add fde4:2:0:56::5/64 dev R5-eth2

ip link set dev R5-eth3 up
ip -6 addr add fde4:2:0:57::5/64 dev R5-eth3

ip link set dev R5-eth4 up
ip -6 addr add fde4:2:0:58::5/64 dev R5-eth4


# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/r5.api -i /tmp/r5_zebra.pid --v6-rr-semantics &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/r5_ospf.conf -z /tmp/r5.api -i /tmp/r5_ospf6d.pid -A 127.0.0.1 &
# launching bgpd
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/r5_bgp.conf -z /tmp/r5.api -i /tmp/r5_bgpd.pid -A 127.0.0.1


