#!/bin/bash

# Abort on error // swap with -x to trace execution (debug)
set -e

# Load global config
#source "$(cd "$(dirname "$0")"; pwd -P)/../myNetwork"
ldconfig

# Add loopback address
ip -6 addr add fde4:2:0:66::6/64 dev lo

# Add the addresses for our public interfaces towards BGP peers
ip link set dev R6-eth0 up
ip -6 addr add fde4:2:0:46::6/64 dev R6-eth0

ip link set dev R6-eth1 up
ip -6 addr add fde4:2:0:56::6/64 dev R6-eth1

ip link set dev R6-eth2 up
ip -6 addr add fde4:2:0:68::6/64 dev R6-eth2

ip link set dev eb1 up
ip -6 addr add fde4::2:cafe/64 dev eb1

ip link set dev ebG6 up
ip -6 addr add fde4::2:baba/64 dev ebG6

# The BELNET - BXL link, defaults to fd00:255:beb1::be/64
#ip address add dev BELNET-eth0 "fde4:2:beb1::be/64"

# Assign an IP address (and an associated subnet prefix length)
# to the fist subnet connected to this router (defaults to fd00:255:be::/48)
#ip address add dev BELNET-lan0 "fde4:2:be::/48"

# zebra is required to make the link between all FRRouting daemons
# and the linux kernel routing table
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/zebra -A 127.0.0.1 -f /etc/zebra.conf -z /tmp/r6.api -i /tmp/r6_zebra.pid --v6-rr-semantics &
# launching FRRouting OSPF daemon
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/ospf6d -f /etc/r6_ospf.conf -z /tmp/r6.api -i /tmp/r6_ospf6d.pid -A 127.0.0.1 &
# launching BGP
LD_LIBRARY_PATH=/usr/local/lib /usr/lib/frr/bgpd -f /etc/r6_bgp.conf -z /tmp/r6.api -i /tmp/r6_bgpd.pid -A 127.0.0.1

