#!/bin/bash
sysctl -w net.ipv6.conf.all.forwarding=1
sysctl -w net.ipv6.conf.default.forwarding=1
echo "R8 has booted"

# As we call this before adding any interfaces, we know that the settings will
# be applied automatically to every new interface
#sysctl -p

